# -*- coding: utf-8 -*-
"""alfara

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zjj_EGV35fdCJXTwO2Q6pt9LDuikw4x4
"""

import streamlit as st
import pickle

# Load the model (function)
with open('arabic_text_processing.pkl', 'rb') as f:
    convert_to_phonetic_and_pattern = pickle.load(f)

# Title of the app
st.title('Arabic Phonetic Converter and CV Pattern Generator')

# Display Al-Farahidi image
st.image("alfarahidi.jpg", caption="Al-Farahidi - Father of Arabic Prosody", use_column_width=True)

st.write("""
### Enter Arabic Text:
This tool applies linguistic rules to convert Arabic text into phonetic writing and CV patterns.
""")

# Text input field
text = st.text_area("Arabic Text Input", "")

# Button for conversion
if st.button('Convert'):
    if text:
        phonetic_output, pattern_output = convert_to_phonetic_and_pattern(text)
        st.write("### Phonetic Writing:")
        st.write(phonetic_output)
        st.write("### CV Pattern:")
        st.write(pattern_output)
    else:
        st.error("Please enter some text to convert.")

